from .colors import DEFAULT_COLORS, GENERIC_COLORS, Color, ColorIterable, ColorType
from .defaults import DefaultSettings, GenericSettings, MaxSettings
from .parameters import AxisParameters, PlotParameters
from .plot_lc import (
    PhotPlotTypes,
    PlotType,
    SNPlotTypes,
    format_axis,
    get_color,
    get_label,
    get_marker,
    get_photcol,
    get_plot_kwargs,
    get_site_markers,
    get_unsub_mark,
    label_axis,
    make_figure,
    make_plot_colors,
    make_plot_shifts,
    make_single_figure,
    plot_abs_mag,
    plot_all_bands,
    plot_band,
    plot_emcee,
    plot_flux,
    plot_lim,
    plot_lims,
    plot_lum,
    plot_mag,
    plot_snake,
    plot_split_by_site,
    update_legend_handles_labels,
)
from .plotter import Plotter
from .premade_plots import AbsMagAxisParams, AbsMagPlotParams, plot_flows_absmag
    
__all__: list[str] = [
    "DEFAULT_COLORS",
    "GENERIC_COLORS",
    "Color",
    "ColorIterable",
    "ColorType",
    "DefaultSettings",
    "GenericSettings",
    "MaxSettings",
    "AxisParameters",
    "PlotParameters",
    "PhotPlotTypes",
    "PlotType",
    "SNPlotTypes",
    "format_axis",
    "get_color",
    "get_label",
    "get_marker",
    "get_photcol",
    "get_plot_kwargs",
    "get_site_markers",
    "get_unsub_mark",
    "label_axis",
    "make_figure",
    "make_plot_colors",
    "make_plot_shifts",
    "make_single_figure",
    "plot_abs_mag",
    "plot_all_bands",
    "plot_band",
    "plot_emcee",
    "plot_flux",
    "plot_lim",
    "plot_lims",
    "plot_lum",
    "plot_mag",
    "plot_snake",
    "plot_split_by_site",
    "update_legend_handles_labels",
    "Plotter",
    "AbsMagAxisParams",
    "AbsMagPlotParams",
    "plot_flows_absmag",
]
