name: Python tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit flake8 black
          flit install --extras all
      - name: setup tendrils
        uses: jannekem/run-python-script-action@v1.3
        with:
          script: |
            import os
            from tendrils.utils import set_api_token
            token = os.environ["FLOWS_TOKEN"]
            set_api_token(token)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FLOWS_TOKEN: ${{ secrets.FLOWS_API_TOKEN }}
      - name: Test with pytest
        run: |
          python -m pytest
